package admin

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"connectrpc.com/connect"
	"github.com/flyteorg/flyte/v2/flytestdlib/logger"
	"github.com/flyteorg/flyte/v2/gen/go/flyteidl2/auth"
	"github.com/flyteorg/flyte/v2/gen/go/flyteidl2/auth/authconnect"
	"google.golang.org/protobuf/proto"

	"github.com/unionai/flyte-sdk-go/flyte/client/cache"
	"github.com/unionai/flyte-sdk-go/flyte/client/externalprocess"
)

const defaultAuthorizationHeader = "authorization"

// authInterceptor injects a bearer token on every RPC. The token source and
// authorization header key are materialized lazily on first use (they may
// require anonymous metadata RPCs and, for PKCE/device flow, a login), and are
// re-materialized once when the server answers Unauthenticated.
type authInterceptor struct {
	cfg        *Config
	tokenCache cache.TokenCache
	authClient authconnect.AuthMetadataServiceClient

	mu          sync.Mutex
	tokenSource TokenSource
	headerKey   string
}

func newAuthInterceptor(cfg *Config, tokenCache cache.TokenCache, authClient authconnect.AuthMetadataServiceClient) *authInterceptor {
	return &authInterceptor{cfg: cfg, tokenCache: tokenCache, authClient: authClient}
}

// bearer returns the header key and value to attach to a request.
func (a *authInterceptor) bearer(ctx context.Context) (string, string, error) {
	a.mu.Lock()
	defer a.mu.Unlock()

	if a.tokenSource == nil {
		if err := a.materialize(ctx); err != nil {
			return "", "", err
		}
	}
	token, err := a.tokenSource.Token()
	if err != nil {
		// The source may hold stale state (e.g. an expired cached login);
		// rebuild it once before giving up.
		if err := a.materialize(ctx); err != nil {
			return "", "", err
		}
		token, err = a.tokenSource.Token()
		if err != nil {
			return "", "", fmt.Errorf("failed to obtain auth token: %w", err)
		}
	}
	return a.headerKey, "Bearer " + token.AccessToken, nil
}

// materialize (re)builds the token source and resolves the authorization
// header key. Callers must hold a.mu.
func (a *authInterceptor) materialize(ctx context.Context) error {
	provider, err := NewTokenSourceProvider(ctx, a.cfg, a.tokenCache, a.authClient)
	if err != nil {
		return fmt.Errorf("failed to initialize token source provider: %w", err)
	}
	source, err := provider.GetTokenSource(ctx)
	if err != nil {
		return err
	}
	a.tokenSource = source

	a.headerKey = a.cfg.AuthorizationHeader
	if a.headerKey == "" {
		resp, err := a.authClient.GetPublicClientConfig(ctx, connect.NewRequest(&auth.GetPublicClientConfigRequest{}))
		if err == nil && resp.Msg.GetAuthorizationMetadataKey() != "" {
			a.headerKey = resp.Msg.GetAuthorizationMetadataKey()
		} else {
			a.headerKey = defaultAuthorizationHeader
		}
	}
	return nil
}

// invalidate drops the current token so the next call re-authenticates.
func (a *authInterceptor) invalidate() {
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.tokenSource != nil {
		if token, err := a.tokenSource.Token(); err == nil {
			if _, err := a.tokenCache.PurgeIfEquals(token); err != nil {
				logger.Debugf(context.Background(), "failed to purge cached token: %v", err)
			}
		}
	}
	a.tokenSource = nil
}

func (a *authInterceptor) WrapUnary(next connect.UnaryFunc) connect.UnaryFunc {
	return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
		key, value, err := a.bearer(ctx)
		if err != nil {
			return nil, err
		}
		req.Header().Set(key, value)
		resp, err := next(ctx, req)
		if err != nil && connect.CodeOf(err) == connect.CodeUnauthenticated {
			logger.Debugf(ctx, "request unauthenticated, re-authenticating once: %v", err)
			a.invalidate()
			if key, value, aerr := a.bearer(ctx); aerr == nil {
				req.Header().Set(key, value)
				return next(ctx, req)
			}
		}
		return resp, err
	}
}

func (a *authInterceptor) WrapStreamingClient(next connect.StreamingClientFunc) connect.StreamingClientFunc {
	return func(ctx context.Context, spec connect.Spec) connect.StreamingClientConn {
		conn := next(ctx, spec)
		if key, value, err := a.bearer(ctx); err == nil {
			conn.RequestHeader().Set(key, value)
		} else {
			logger.Errorf(ctx, "failed to attach auth token to stream: %v", err)
		}
		return conn
	}
}

func (a *authInterceptor) WrapStreamingHandler(next connect.StreamingHandlerFunc) connect.StreamingHandlerFunc {
	return next // client-only interceptor
}

// proxyAuthInterceptor attaches a proxy-authorization header generated by an
// external command, for deployments behind an authenticating proxy.
type proxyAuthInterceptor struct {
	command []string
}

const proxyAuthorizationHeader = "proxy-authorization"

func (p *proxyAuthInterceptor) token() (string, error) {
	output, err := externalprocess.Execute(p.command)
	if err != nil {
		return "", err
	}
	return "Bearer " + strings.Trim(string(output), "\t \n"), nil
}

func (p *proxyAuthInterceptor) WrapUnary(next connect.UnaryFunc) connect.UnaryFunc {
	return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
		value, err := p.token()
		if err != nil {
			return nil, fmt.Errorf("failed to generate proxy-authorization token: %w", err)
		}
		req.Header().Set(proxyAuthorizationHeader, value)
		return next(ctx, req)
	}
}

func (p *proxyAuthInterceptor) WrapStreamingClient(next connect.StreamingClientFunc) connect.StreamingClientFunc {
	return func(ctx context.Context, spec connect.Spec) connect.StreamingClientConn {
		conn := next(ctx, spec)
		if value, err := p.token(); err == nil {
			conn.RequestHeader().Set(proxyAuthorizationHeader, value)
		}
		return conn
	}
}

func (p *proxyAuthInterceptor) WrapStreamingHandler(next connect.StreamingHandlerFunc) connect.StreamingHandlerFunc {
	return next
}

// orgInterceptor fills empty Org fields on outgoing request protos with the
// configured default org.
type orgInterceptor struct {
	org string
}

func (o *orgInterceptor) WrapUnary(next connect.UnaryFunc) connect.UnaryFunc {
	return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
		if msg, ok := req.Any().(proto.Message); ok {
			replaceOrgFieldIfEmpty(msg, o.org)
		}
		return next(ctx, req)
	}
}

func (o *orgInterceptor) WrapStreamingClient(next connect.StreamingClientFunc) connect.StreamingClientFunc {
	return func(ctx context.Context, spec connect.Spec) connect.StreamingClientConn {
		return &orgStreamingConn{StreamingClientConn: next(ctx, spec), org: o.org}
	}
}

func (o *orgInterceptor) WrapStreamingHandler(next connect.StreamingHandlerFunc) connect.StreamingHandlerFunc {
	return next
}

type orgStreamingConn struct {
	connect.StreamingClientConn
	org string
}

func (c *orgStreamingConn) Send(msg any) error {
	if pm, ok := msg.(proto.Message); ok {
		replaceOrgFieldIfEmpty(pm, c.org)
	}
	return c.StreamingClientConn.Send(msg)
}

// retryInterceptor retries unary RPCs that fail with Unavailable, with linear
// backoff, mirroring the retry policy of the Python SDK's client.
type retryInterceptor struct {
	maxRetries int
	maxBackoff time.Duration
}

func (r *retryInterceptor) WrapUnary(next connect.UnaryFunc) connect.UnaryFunc {
	return func(ctx context.Context, req connect.AnyRequest) (connect.AnyResponse, error) {
		var resp connect.AnyResponse
		var err error
		for attempt := 0; ; attempt++ {
			resp, err = next(ctx, req)
			if err == nil || connect.CodeOf(err) != connect.CodeUnavailable || attempt >= r.maxRetries {
				return resp, err
			}
			backoff := time.Duration(attempt+1) * 250 * time.Millisecond
			if r.maxBackoff > 0 && backoff > r.maxBackoff {
				backoff = r.maxBackoff
			}
			select {
			case <-time.After(backoff):
			case <-ctx.Done():
				return nil, ctx.Err()
			}
		}
	}
}

func (r *retryInterceptor) WrapStreamingClient(next connect.StreamingClientFunc) connect.StreamingClientFunc {
	return next // stream consumers handle reconnects themselves
}

func (r *retryInterceptor) WrapStreamingHandler(next connect.StreamingHandlerFunc) connect.StreamingHandlerFunc {
	return next
}

// replaceOrgFieldIfEmpty recursively replaces "Org" field values in proto messages if they are empty
func replaceOrgFieldIfEmpty(msg proto.Message, org string) {
	visited := make(map[uintptr]bool)
	replaceOrgIfEmptyHelper(reflect.ValueOf(msg).Elem(), visited, org)
}

func replaceOrgIfEmptyHelper(val reflect.Value, visited map[uintptr]bool, org string) {
	if !val.IsValid() {
		return
	}
	// Only mark the actual struct instances as visited
	if val.Kind() == reflect.Ptr && !val.IsNil() {
		addr := val.Pointer()
		if visited[addr] {
			return
		}
		visited[addr] = true
	}

	switch val.Kind() {
	case reflect.Ptr:
		if !val.IsNil() {
			replaceOrgIfEmptyHelper(val.Elem(), visited, org)
		}
	case reflect.Struct:
		for i := 0; i < val.NumField(); i++ {
			field := val.Field(i)
			fieldType := val.Type().Field(i)
			if fieldType.Name == "Org" && field.Kind() == reflect.String && field.String() == "" {
				field.SetString(org)
			} else if fieldType.Tag.Get("protobuf_oneof") != "" {
				// Handle oneof fields
				if !field.IsNil() {
					oneofField := field.Elem()
					replaceOrgIfEmptyHelper(oneofField, visited, org)
				}
			} else {
				replaceOrgIfEmptyHelper(field, visited, org)
			}
		}
	case reflect.Slice:
		for i := 0; i < val.Len(); i++ {
			replaceOrgIfEmptyHelper(val.Index(i), visited, org)
		}
	case reflect.Interface:
		if !val.IsNil() {
			replaceOrgIfEmptyHelper(val.Elem(), visited, org)
		}
	}
}
